### PR TITLE
 If the user desires , you want to capture a column of type TEXT as a String

### PR DESCRIPTION
**Pull request by meru-akimbo**
If user want to import a table that contains a TEXT type table , in the current version , it is not possible to use this module .
I think that it should be possible, if the user wishes.

Add allow_text_type option.
When this option is enable, TEXT type columns also import as string.

### CODE REVIEW

**Comment by pine** [comment]
@myfinder 👍

**Comment by myfinder** [comment]
thank you for your p-r, I will check this weekend.

**Comment by myfinder** [comment]
It looks like good to me.
do you think about this p-r? @cou929 and @yoheimuta

**Comment by yoheimuta** [comment]
It seems good to me. 👍

**Comment by meru-akimbo** [comment]
thank you review 🙏

**Comment by myfinder** [comment]
@meru-akimbo @punytan : I defined you co-maintener setting.

image

**Comment by karupanerura** [comment]
@meru-akimbo ++

**Comment by meru-akimbo** [comment]
@myfinder 

Sry, I try new release this module.
But, I faild complete. I was able to release to the cpan but failed to push to github.

Would you add me to cotributor of github?

**Pull request merged**
