### PR TITLE
Fixed: automatically removed a tempfile when the program exits

### PR DESCRIPTION
**Pull request by yoheimuta**
[Default is for the file to be removed if a file handle is requested and to be kept if the filename is requested](https://metacpan.org/pod/File::Temp#tempfile).

### CODE REVIEW

**Comment by yoheimuta** [comment]
I want to merge this and release the upgraded version(maybe v0.03).

@myfinder @cou929 Could you review this PR ?

**Comment by cou929** [comment]
LGTM 👍

**Comment by yoheimuta** [comment]
Thx !

**Comment by myfinder** [comment]
thank you for your p-r, I will check this weekend.

**Pull request merged**
